version: '2'

services:
  klipper:
    image: cberg18/klipper-moonraker
    build:
      dockerfile: ./klipper/Dockerfile
      context: .
    cap_add:
      - SYS_NICE
    container_name: klipper
    ports:
      - 7125:7125
    restart: unless-stopped
    volumes:      
      - gcode_files:/home/klippy/printer_data/gcodes
      - /mnt/configs/kms/config:/home/klippy/printer_data/config
      - moonraker_data:/home/klippy/.moonraker_database
      
    devices:
      - /dev/ttyACM0:/dev/ttyACM0

  fluidd:
    image: cberg18/fluidd
    restart: unless-stopped
    container_name: fluidd
    ports:
      - 8010:80
    depends_on: 
      - klipper
    links:
      - klipper:klipper

volumes: 
  gcode_files:
  moonraker_data:

